### PR TITLE
Widget to display content

### PR DESCRIPTION
**Pull request by zzuga**
An easy way to add generic widgets

### CODE REVIEW

**Comment by adamf321** [comment]
@zzuga this looks the same as the LeeanPreview widget to me...

**Comment by zzuga** [comment]
If only description was a textarea in LeeanPreview, I could use it.

Shall I change that instead of adding a new one? do you think its safe?

**Comment by adamf321** [comment]
Yes, I think we could make it a textarea without breaking existing widgets

**Comment by zzuga** [comment]
Then its much simpler, thanks!

**Pull request merged**
